org.gradle.jvmargs=-Xmx8192m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
systemProp.gradle.http.client.protocol=TLSv1.2
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
